language: scala
scala:
  - 2.11.7

script:
  - sbt clean coverage test coverageReport

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coveralls

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

# Travis is unable to start neo4j in a container
# See https://github.com/travis-ci/travis-ci/issues/3243
#services:
# - neo4j

# Work-around solution is to install manually:
env:
  - NEO4J_URL="http://localhost:7474"
jdk:
  - oraclejdk8
before_install:
  - wget dist.neo4j.org/neo4j-community-2.3.2-unix.tar.gz
  - tar -xzf neo4j-community-2.3.2-unix.tar.gz
  # Disable required password
  # - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.3.2/conf/neo4j-server.properties
  - neo4j-community-2.3.2/bin/neo4j start

